name: Append build number to version

inputs:
  package:
    description: Package name
    required: true

runs:
  using: composite
  steps:
    - name: Setup env
      run: python $GITHUB_ACTION_PATH/buildnum_env.py >> $GITHUB_ENV
      shell: bash

    - name: Print version numbers
      run: |
        echo -e "Old Version: ${{ env.old-version }}"
        echo -e "New Version: ${{ env.new-version }}"
      shell: bash

    - name: Append build number to version
      env:
        OLD_VERSION_LINE: ^__version__ *= *\"${{ env.old-version }}\" *$
        NEW_VERSION_LINE: __version__ = \"${{ env.new-version }}\"
      run: sed -i "s/${OLD_VERSION_LINE}/${NEW_VERSION_LINE}/" "${{ env.package-name }}/__init__.py"
      shell: bash
